config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create', as: 'login'
  get '/auth/failure', to: 'sessions#create'
  get '/logout', to: 'sessions#delete'

  resources :user, only: :show do
    resources :artists, controller: 'user_artists' do
      resources :art_pieces, only: [:create, :new,:edit, :update, :destroy]
    end
  end

  resources :public_gallery, only: :index
  resources :inspiration, only: :index
  resources :account_management, only: :index
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/account_management_controller.rb
# frozen_string_literal: true

class AccountManagementController < ApplicationController
  def index
    @artists = UserArtistsFacade.artists(current_user.id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    BackendFacade.current_user(session[:user]) if session[:user]
  end
end

app/controllers/art_pieces_controller.rb
# frozen_string_literal: true

class ArtPiecesController < ApplicationController
  def new
    @artist = UserArtistsFacade.artist(current_user.id, params[:artist_id])
  end

  def create
    artist = UserArtistsFacade.artist(current_user.id, params[:artist_id])
    image = params[:image_upload]
    md5_hash = Digest::MD5.base64digest(image.read)
    presigned_params = {
      filename: image.original_filename,
      byte_size: image.size,
      checksum: md5_hash,
      content_type: image.content_type,
      metadata: {}
    }
    presigned_response = BackendService.request_presigned_url(presigned_params)
    sleep 5
    presigned_url = presigned_response[:direct_upload][:url]
    blob = presigned_response[:blob_signed_id]
    file = Faraday::UploadIO.new(
      image.tempfile.path,
      image.content_type,
      image.original_filename
    )
    amazon_response = Faraday.put(presigned_url) do |req|
      req.headers['Content-Type'] = image.content_type
      req.headers['Content-MD5'] = md5_hash
      req.body = file.read
    end
    params_hash = {
      title: params[:art_piece_title],
      description: params[:art_piece_description],
      image: blob
    }
    BackendService.create_image(current_user.id, artist.id, params_hash)
  end

  def update
    BackendFacade.update_image(image_params, params[:id])
    redirect_to user_artist_path(current_user.id, params[:artist_id])
  end

  def destroy
    BackendFacade.delete_image(params[:artist_id], image_id)
    redirect_to user_artist_path(current_user.id, params[:artist_id])
  end

  private

  def artist_params
    params.permit(:username, :password, :password_confirmation, :user_id)
  end

  def image_params
    params.permit(:art_piece_title, :art_piece_description)
  end
end

app/controllers/inspiration_controller.rb
# frozen_string_literal: true

class InspirationController < ApplicationController
  def index
    @image = BackendFacade.inspiration_image if params[:image]
  end
end

app/controllers/public_gallery_controller.rb
# frozen_string_literal: true

class PublicGalleryController < ApplicationController
  def index
    @public_images = BackendFacade.public_images
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    if auth_hash == :invalid_credentials
      flash[:error] = 'Oops, something went wrong!'
      redirect_to root_path
    else
      user_info = {
        google_id: auth_hash['uid'],
        email: auth_hash['info']['email'],
        token: auth_hash['credentials']['token']
      }
      user = BackendFacade.user(user_info)
      session[:user] = user.id
      redirect_to user_artists_path(user.id)
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_artists_controller.rb
# frozen_string_literal: true

class UserArtistsController < ApplicationController
  def index
    @artists = UserArtistsFacade.artists(current_user.id)
  end

  def show
    @artist = UserArtistsFacade.artist(current_user.id, params[:id])
    @images = BackendFacade.artist_images(params[:id])
  end

  def new; end

  def create
    if artist_params[:password] == artist_params[:password_confirmation]
      UserArtistsFacade.create(artist_params)
      redirect_to user_artists_path(current_user.id)
    else
      # flash[:danger] = 'Passwords do not match!'
      redirect_to new_user_artist_path(current_user.id)
    end
  end

  def edit
    @artist = UserArtistsFacade.artist(current_user.id, params[:id])
  end

  def update
    if artist_params[:password] == artist_params[:password_confirmation]
      UserArtistsFacade.update(artist_params, params[:id])
      redirect_to account_management_index_path
    else
      flash[:error] = 'Passwords do not match!'
      redirect_to edit_user_artist_path(params[:user_id], params[:id])
    end
  end

  def destroy
    UserArtistsFacade.delete(params[:user_id], params[:id])
    redirect_to account_management_index_path
  end

  private

  def artist_params
    params.permit(:username, :password, :password_confirmation, :user_id)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/account_management/index.html.erb
<div id='header'>
  <h1>Account Management</h1>
</div>

<div id='artists'>
  <% @artists.each do |artist| %>
  <div id='artist-<%= artist.id %>'>
    <%= artist.username %>
    <%= button_to 'Edit', edit_user_artist_path(current_user.id, artist.id), method: :get %>
    <%= button_to 'Delete', "/user/#{current_user.id}/artists/#{artist.id}", method: :delete %>
  </div>
  <% end %>
</div>

app/views/art_pieces/new.html.erb
<div id="header"
  <h1>Upload an Art Piece</h1>
</div>

<div id="upload_form">
  <%= form_with url: user_artist_art_pieces_path, local: true do |f| %>
    <%= f.label :art_piece_title,  "Name Your New Art Piece:" %>
    <%= f.text_field :art_piece_title, id: :art_piece_title %> <br>
    <%= f.label :art_piece_description,  "Describe Your Art Piece:" %>
    <%= f.text_field :art_piece_description, id: :art_piece_description %> <br>
    <%= f.label :image_upload %>
    <%= f.file_field :image_upload, id: :image_upload, accept: "image/jpeg" %> <br>
    <%= f.submit "Create Art Piece" %>
<% end %>
</div>

app/views/inspiration/index.html.erb
<div id="header">
  <h1 class="text-center">Find Inspiration</h1>
</div>

<div class="text-center" id="picture">
  <% unless @image.nil? %>
    <%= image_tag(@image.url, alt: 'Random Image') %>
  <% end %><br><br>
  <%= link_to 'Randomize my Picture!', method: :get, params: { image: true } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TikiarteFe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
    <% end %>
    <% unless current_user.nil? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="<%= user_artists_path(current_user.id) %>">Director Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= public_gallery_index_path %>">Public Gallery</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= inspiration_index_path %>">Find Inspiration</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= account_management_index_path %>">Account Management</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= logout_path %>">Logout</a>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/public_gallery/index.html.erb
<div id="header">
  <h1 class="text-center">Public Gallery</h1>
</div>

<% if @public_images.nil? == false %>
  <div id="images">
    <div class="row">
      <% @public_images.each do |image| %>
      <div class="col-lg-4 mb-4 mb-lg-0">
        <img
          src="<%= image.url %>"
          class="w-100 shadow-1-strong rounded mb-4"
          alt="<%= image.title %>"
        />
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/user_artists/edit.html.erb
<div id='header'>
  <h1>Edit <%= @artist.username %></h1>
</div>

<div id='form'>
  <%= form_with url: "/user/#{current_user.id}/artists/#{@artist.id}", method: :put, local: true do |form| %>
  <%= form.label :username, 'Username:' %>
  <%= form.text_field :username, id: 'username', value: @artist.username %>
  <%= form.label :password, 'Password:' %>
  <%= form.password_field :password, id: 'password' %>
  <%= form.password_field :password_confirmation, id: 'password_confirmation' %>
  <%= form.submit 'Edit Artist' %>
<% end %>
</div>

app/views/user_artists/index.html.erb
<div id='header'>
  <h1>My Artists</h1>
</div>

<div id='artists'>
  <% if @artists.count > 0  %>
    <% @artists.each do |artist| %>
      <p><%= artist.username %></p>
      <p><%= button_to "#{artist.username}'s Portfolio Page", user_artist_path(current_user.id, artist.id), method: :get %></p>
    <% end %>
    <%= button_to 'Add Artist', new_user_artist_path(current_user.id), method: :get %>
  <% else %>
    <p>You haven't added any Artists to your account yet.</p>
      <%= button_to 'Add Artist', new_user_artist_path(current_user.id), method: :get %>
  <% end %>
</div>

app/views/user_artists/new.html.erb
<div id='header'>
  <h1>Add a New Artist</h1>
</div>

<div id='form'>
  <%= form_with url: user_artists_path(current_user.id), method: :post, local: true do |form| %>
  <%= form.label :username, 'Username:' %>
  <%= form.text_field :username, id: 'username' %>
  <%= form.label :password, 'Password:' %>
  <%= form.password_field :password, id: 'password' %>
  <%= form.password_field :password_confirmation, id: 'password_confirmation' %>
  <%= form.submit 'Add Artist' %>
<% end %>
</div>

app/views/user_artists/show.html.erb
<div align='center' id='header'>
  <h1><%= @artist.username %>'s Portfolio</h1>
  <a href="<%= new_user_artist_art_piece_path(current_user.id, @artist.id) %>">Upload an Art Piece</a>
</div>

<% if @images.nil? == false %>
<div id="count">
  <h3 class="text-center">Total Art Pieces: <%= @images.count %></h3>
</div>

  <div id="private-gallery">
    <h4 class="text-center">Private Artwork</h4>
    <div class="row">
    <% @images.each do |image| %>
      <% if image.status == 'private' %>
        <div class="col-lg-3 mb-3 mb-3 mb-lg-0">
          <img
            src="<%= image.url %>"
            class="w-100 shadow-1-strong rounded mb-4"
            alt="<%= image.title %>"
            style=""
          />
        </div>
        <div class="desc"><%= image.description %></div>
        <%= form_with url: "/user/#{current_user.id}/artists/#{@artist.id}/art_pieces/#{image.id}", method: :put, local: true do |f| %>
          <%= f.hidden_field :status, value: 'public' %>
          <%= f.submit 'Make Public' %>
        <% end %>
        <%= link_to 'Delete', "/user/#{current_user.id}/artists/#{@artist.id}/art_pieces/#{image.id}", method: :delete %>
      <% end %>
    <% end %>
    </div>
  </div>

  <div id="public-gallery">
    <h4 class="text-center">Artwork Currently Freatured in Public Gallery</h4>
    <div class="row">
      <% @images.each do |image| %>
        <% if image.status == 'public' %>
        <div class="col-lg-3 mb-3 mb-3 mb-lg-0">
          <img
            src="<%= image.url %>"
            class="w-100 shadow-1-strong rounded mb-4"
            alt="<%= image.title %>"
          />
        </div>
        <div class="desc"><%= image.description %></div>
        <%= form_with url: "/user/#{current_user.id}/artists/#{@artist.id}/art_pieces/#{image.id}", method: :put, local: true do |f| %>
          <%= f.hidden_field :status, value: 'private' %>
          <%= f.submit 'Make Public' %>
        <% end %>
        <%= link_to 'Delete', "/user/#{current_user.id}/artists/#{@artist.id}/art_pieces/#{image.id}", method: :delete %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<div id="header">
  <h1 style="text-align: center">Tikiarté</h1>
</div>

<div id="welcome-message">
  <h3 style="text-align: center">Welcome to Tikiarté!</h3>
</div>

<div class="col text-center" id="button">
  <%= button_to 'Sign in with Google', '/auth/google_oauth2', method: :get %>
</div>